package consts

// Telegram only allows 64 bytes in callback_data,
// So we have to be really short :)
const (
	CmdShowStart                   = "start"
	CmdDoNothing                   = "nothing"
	CmdShowLater                   = "later"
	CmdShowToday                   = "today"
	CmdShowFiles                   = "files"
	CmdShowPostpone                = "postpone"
	CmdShowMoveFromToday           = "move"
	CmdShowMoveTo                  = "s_move"
	CmdShowRename                  = "rename"
	CmdShowRenameFile              = "rename_file"
	CmdShowChecklists              = "checklists"
	CmdShowStats                   = "stats"
	CmdShowHelp                    = "help"
	CmdComplete                    = "c"
	CmdPostpone                    = "post"
	CmdShowMultilineTask           = "task"
	CmdShowFile                    = "file"
	CmdShowChecklist               = "checklist"
	CmdShowChecklistItem           = "check_show"
	CmdCompleteChecklistItem       = "check_comp"
	CmdShowMoveToDirOrFile         = "to_file"
	CmdShowMoveToChecklist         = "to_checklist"
	CmdRename                      = "ren"
	CmdMoveToDir                   = "mv"
	CmdRequestNewDir               = "new_dir"
	CmdMoveToNewDir                = "mv_to_new_dir"
	CmdMoveToExistingFile          = "mf"
	CmdMoveToExistingNote          = "mvn"
	CmdMoveToNewFile               = "mn"
	CmdMoveToChecklist             = "mv_to_chk"
	CmdMoveToRead                  = "mv_to_read"
	CmdMoveToWatch                 = "mv_to_watch"
	CmdMoveToShop                  = "mv_to_shop"
	CmdMoveToNewChecklist          = "mv_to_new_chk"
	CmdMoveToJournal               = "mv_to_journal"
	CmdMoveToLater                 = "mv_later"
	CmdShowScheduleForDay          = "sc_day"
	CmdSchedule                    = "sc"
	CmdScheduleForTmrw             = "sc_tmrw"
	CmdPomodoro                    = "pomodoro"
	CmdShowScheduleForDayRecurring = "sc_day_r"
	CmdLater                       = "later"
	CmdShowSettings                = "settings"
	CmdShowQuickBtnsSettings       = "c_quick_btns"
	CmdShowMoveToBtnsSettings      = "c_move_btns"
	CmdAddToQuickBtns              = "add_quick"
	CmdDelFromQuickBtns            = "del_quick"
	CmdAddToMoveToBtns             = "add_move"
	CmdDelFromMoveToBtns           = "del_move"
	CmdShowReadChecklist           = "read"
	CmdShowWatchChecklist          = "watch"
	CmdShowShopChecklist           = "shop"
	CmdShowSchedule                = "schedule"
	CmdInlineQuerySearchEveryWhere = "search"
	CmdInlineQuerySearchInDir      = "search_dir"
	CmdWebAppHabits                = "habits"
	CmdAddToJournalShortcut        = "j"
	CmdAddToRecentFileShortcut     = "+"
)

var (
	Shortcuts = map[string][]string{
		CmdAddToJournalShortcut:    {"/ж", "jj", "жж"},
		CmdAddToRecentFileShortcut: {"++"},
	}
)
