package constants

const (
	CmdShowStart          = "start"
	CmdShowLater          = "later"
	CmdShowToday          = "today"
	CmdShowNotes          = "notes"
	CmdShowPostpone       = "postpone"
	CmdShowDocs           = "docs"
	CmdShowRename         = "rename"
	CmdShowChecklists     = "checklists"
	CmdShowStats          = "stats"
	CmdComplete           = "comp"
	CmdPostpone           = "post"
	CmdRenameFile         = "rename_file"
	CmdShowMultilineTask  = "task"
	CmdShowDoc            = "doc"
	CmdShowChecklist      = "checklist"
	CmdShowChooseDay      = "to_day"
	CmdShowToNote         = "to_note"
	CmdShowToDoc          = "to_doc"
	CmdShowToChecklist    = "to_checklist"
	CmdMove               = "mv"
	CmdMoveToNewDir       = "mv_to_new_dir"
	CmdMoveToDoc          = "mv_to_doc"
	CmdMoveToNewDoc       = "mv_to_new_doc"
	CmdMoveToChecklist    = "mv_to_chk"
	CmdMoveToNewChecklist = "mv_to_new_chk"
	CmdMoveJournal        = "mv_to_journal"
	CmdSchedule           = "sc"
	CmdPomodoro           = "pomodoro"
	CmdShowRecurringKB    = "recur_kb"
	CmdTomorrow           = "tomorrow"
	CmdLater              = "later"
	CmdShowSettings       = "settings"
	CmdConfigurePanel     = "configure_panel"
	CmdAddToPanel         = "panel_add"
	CmdDelFromPonel       = "panel_del"
)
