package consts

// Telegram only allows 64 bytes in callback_data,
// So we have to be really short :)
const (
	CmdShowStart                       = "start"
	CmdDoNothing                       = "nothing"
	CmdShowLater                       = "later"
	CmdShowToday                       = "today"
	CmdShowFiles                       = "files"
	CmdShowDirs                        = "dirs"
	CmdShowPostpone                    = "postpone"
	CmdShowMoveFromToday               = "move"
	CmdShowMoveTo                      = "s_move"
	CmdShowMoveToFromToday             = "s_move_t"
	CmdShowRename                      = "rename"
	CmdShowRenameFile                  = "rename_file"
	CmdShowChecklists                  = "checklists"
	CmdShowStats                       = "stats"
	CmdOpenInApp                       = "app"
	CmdShowHelp                        = "help"
	CmdComplete                        = "c"
	CmdCompleteFromInbox               = "c_ch"
	CmdPostpone                        = "post"
	CmdShowMultilineTask               = "task"
	CmdShowLongItem                    = "item"
	CmdShowLongItemFromInbox           = "item_i"
	CmdShowFile                        = "file"
	CmdShowChecklist                   = "checklist"
	CmdShowChecklistItem               = "check_show"
	CmdCompleteListItem                = "check_comp"
	CmdShowMoveToDirOrFile             = "to_file"
	CmdShowMoveToChecklist             = "to_checklist"
	CmdRename                          = "ren"
	CmdMoveToExistingDir               = "mv"
	CmdMoveToChecklist                 = "add_item"
	CmdCompleteChecklistItem           = "check_item"
	CmdMoveToExistingDirFromToday      = "mv_t"
	CmdRequestNewDir                   = "new_dir"
	CmdMoveToNewDir                    = "mv_to_new_dir"
	CmdMoveToExistingFile              = "mf"
	CmdMoveToExistingNote              = "mvn"
	CmdMoveToNewFile                   = "mn"
	CmdMoveToDirChecklist              = "mv_to_chk"
	CmdMoveToRead                      = "mv_to_read"
	CmdMoveToWatch                     = "mv_to_watch"
	CmdMoveToShop                      = "mv_to_shop"
	CmdMoveToNewChecklist              = "mv_to_new_chk"
	CmdMoveToJournal                   = "mv_to_journal"
	CmdMoveToLater                     = "mv_later"
	CmdShowScheduleForDay              = "sc_day"
	CmdSchedule                        = "sc"
	CmdScheduleForTmrw                 = "sc_tmrw"
	CmdPomodoro                        = "pomodoro"
	CmdShowScheduleForDayRecurring     = "sc_day_r"
	CmdLater                           = "later"
	CmdShowSettings                    = "settings"
	CmdShowQuickBtnsSettings           = "c_quick_btns"
	CmdShowMoveToBtnsSettings          = "c_move_btns"
	CmdAddToQuickBtns                  = "add_quick"
	CmdDelFromQuickBtns                = "del_quick"
	CmdAddToMoveToBtns                 = "add_move"
	CmdDelFromMoveToBtns               = "del_move"
	CmdShowTimezone                    = "timezone"
	CmdSetTimezone                     = "set_timezone"
	CmdShowReadChecklist               = "read"
	CmdShowWatchChecklist              = "watch"
	CmdShowShopChecklist               = "shop"
	CmdShowSchedule                    = "schedule"
	CmdDownload                        = "download"
	CmdTasksOnlyMode                   = "tasks_only"
	CmdNotesOnlyMode                   = "notes_only"
	CmdJournalOnlyMode                 = "journal_only"
	CmdFullMode                        = "full"
	CmdChatMode                        = "chat"
	CmdInlineQuerySearchEveryWhere     = "search"
	CmdInlineQuerySearchInDir          = "search_dir"
	CmdWebAppHabits                    = "habits"
	CmdAddToJournalShortcut            = "j"
	CmdAddToJournalAndContinueShortcut = "ja"
	CmdAddToRecentFileShortcut         = "+"
	CmdCompleteHabit                   = "ch"
	CmdShare                           = "share"
)

var Shortcuts = map[string][]string{
	CmdAddToJournalShortcut:            {"/ж", "jj", "жж"},
	CmdAddToJournalAndContinueShortcut: {"жд", "jd", "ja"},
	CmdAddToRecentFileShortcut:         {"++"},
}
